### PR TITLE
Make phone.py actually randomly generate "human-inputted" phone strings

### PR DESCRIPTION
**Pull request by kavedder**
I'm assuming this is a typo? Thank you for this.

### CODE REVIEW

**Comment by kavedder** [comment]
Actually should be >= or something.

**Comment by graevy** [comment]
no that's intentional; it's just two coin tosses

maybe you're forgetting that random() is instantiating 2 different [0,1) values? the first coin toss replaces spaces with hyphens and the second removes spaces entirely if the first doesn't trigger.

i should probably comment my code better but that's just a hack until i get an address->areacode map after i'm done with LLM text prompt generation and some testing

**Comment by boiled-water-tsar** [comment]
If you want to make it slightly clearer on immediate inspection you could change it to

```python
        if random.choice([0,1]):
            res = res.replace(' ', '-')
        else:
            res = res.replace(' ','')
```

or

```python
        if random.randint(0, 1):
            res = res.replace(' ', '-')
        else:
            res = res.replace(' ','')
```

**Comment by kavedder** [comment]
Ah, of course.

**Pull request closed without merging**
